### ISSUE TITLE
build: create tool to generate app manifest and safari bookmark to home screen meta tags

### ISSUE THREAD

**Issue by jeffbcross** [angular/issue-zero#10]
- [ ] Should be a simple copy-paste operation.
- [ ] Should generate iOS safari meta tags and icons, etc
- [ ] Stretch: bake in to CLI
