### ISSUE TITLE
get firebase hosting and subdomains set up for all angular.io microsites

### ISSUE THREAD

**Issue by jeffbcross** [angular/issue-zero#39]
- [x] Create Firebases for mobile.*, protractor.*, universal.*, material.*
 - [x] Add collaborators
 - [ ] Get subdomains added in Firebase
 - [ ] Create DNS records
