### ISSUE TITLE
progressive checklist

### ISSUE THREAD

**Issue by jeffbcross** [angular/issue-zero#40]
Checklist of technical features to satisfy the definition of a Progressive Web App:
- [ ] App Manifest exists (install to home screen prompt)
- [ ] Manifest has theme_color, background_color, >= 192px icons
- [ ] Registered SW with caching of app shell and static assets
- [ ] Push notifications (optional)
- [ ] App navigable without browser back button
- [x] App shell has viewport meta tag
- [x] App shell exists with network-unblocked critical render path
- [x] Site served on HTTPS
